apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: web-app
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/managed-by: compose2k8s
spec:
  selector:
    app.kubernetes.io/name: api
  ports:
    - port: 3000
      name: tcp-3000
