apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: web-app
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: compose2k8s
spec:
  selector:
    app.kubernetes.io/name: nginx
  ports:
    - port: 80
      name: tcp-80
