apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: web-app
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: compose2k8s
type: Opaque
stringData:
  POSTGRES_PASSWORD: REPLACE_ME
