apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-mosquitto-mosquitto-conf
  namespace: mqtt
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/managed-by: compose2k8s
data:
  mosquitto.conf: |
    listener 1883
    allow_anonymous true
    persistence true
    persistence_location /mosquitto/data/
