apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mqtt
  labels:
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/managed-by: compose2k8s
spec:
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
    - port: 1883
      name: tcp-1883
