apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: fullstack
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/managed-by: compose2k8s
type: Opaque
stringData:
  DATABASE_URL: REPLACE_ME
  REDIS_URL: REPLACE_ME
  API_SECRET: REPLACE_ME
