apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-nginx-default-conf
  namespace: fullstack
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/managed-by: compose2k8s
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            proxy_pass http://api:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
