apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-env
  namespace: fullstack
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: compose2k8s
data:
  POSTGRES_USER: user
  POSTGRES_DB: myapp
