apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fullstack
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: compose2k8s
spec:
  selector:
    app.kubernetes.io/name: postgres
  ports:
    - port: 5432
      name: tcp-5432
