apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: fullstack
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/managed-by: compose2k8s
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      name: tcp-6379
